# Generated by Django 5.0 on 2024-02-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
